Some fixes
shamirlabs/docs pull request #12
Opened 2023-09-01 14:47 UTC by bertho-zero

2023-09-01 18:25 UTC, micho commented
Nice one :) I support this PR, as the previous one was duplicating the `cd` commands

2023-09-04 00:09 UTC, pradavc requested changes
The `cd diva-alpha-net` lines were not duplicated but placed intentionally to make all the commands work agnostic to the path from which the user executes them. Relative paths were used in the previous version because I didn't want to enforce a strict path for the clone in users' systems.

Since you want to avoid confusion (and I agree that for this guide level, it is better), we can assume that the clone is done to the home path. In that case, it is better to remove the `cd` line after the `git clone`, which is useless, enforce cloning to the home path, and keep the `cd` command lines inside the doc of each option of the script (update, install, etc). That way, no matter where the user starts reading, it will always work (even if it comes back directly for the update instructions only, which currently assumes that the user is under `$HOME/diva-alpha-net` when it isn't).

2023-09-04 00:09 UTC, pradavc commented on docs/testnet/install/download.md
> +git clone https://github.com/shamirlabs/diva-alpha-net
```suggestion
git clone https://github.com/shamirlabs/diva-alpha-net ~/diva-alpha-net
```

2023-09-04 00:09 UTC, pradavc commented on docs/testnet/install/download.md
> +cd diva-alpha-net
```suggestion
```

2023-09-04 00:09 UTC, pradavc commented on docs/testnet/install/scripts/install-diva.md
>  ./run.sh
```suggestion
cd ~/diva-alpha-net
./run.sh
```

2023-09-04 00:09 UTC, pradavc commented on docs/testnet/install/scripts/install-docker.md
>  ./run.sh
```suggestion
cd ~/diva-alpha-net
./run.sh
```

2023-09-04 00:09 UTC, pradavc commented on docs/testnet/update-diva.md
>  ./run.sh
```suggestion
cd ~/diva-alpha-net
./run.sh
```

2023-09-07 09:13 UTC, micho commented
lgtm

2023-09-07 14:47 UTC, merged