update section
shamirlabs/docs pull request #20
Opened 2023-09-14 17:58 UTC by franjoespejo

2023-09-15 12:48 UTC, pradavc requested changes

2023-09-15 12:48 UTC, pradavc commented on docs/testnet/update-diva.md
> +### 2. Create a new one
Better title. A new what?

2023-09-15 12:48 UTC, pradavc commented on docs/testnet/update-diva.md
> +## 2. Manual
This should go to a separate section

2023-09-15 20:28 UTC, franjoespejo commented on docs/testnet/update-diva.md
> +## 2. Manual
[done ](https://github.com/shamirlabs/docs/pull/20/commits/f3dfc7658359047af4625759bb15e2794400950c)

2023-09-15 20:28 UTC, franjoespejo commented on docs/testnet/update-diva.md
> +### 2. Create a new one
done https://github.com/shamirlabs/docs/pull/20/commits/8d680ad0c6a6289f657cb87ce7df29c2d472565f

2023-09-16 14:38 UTC, pradavc requested changes

2023-09-16 14:38 UTC, pradavc commented on docs/testnet/update/update-diva-manual.md
> +- Your Ethereum client folders (optional)
I don't understand what this means. What do you mean by listing all these?

2023-09-16 14:38 UTC, pradavc commented on docs/testnet/update/update-diva-manual.md
> +
Instead of this, add a command to navigate to such a folder.

2023-09-16 14:38 UTC, pradavc commented on docs/testnet/update/update-diva-manual.md
> +```
```suggestion
```bash
cd ~/diva-alpha-net
docker compose down 
```
```

2023-09-16 14:38 UTC, pradavc commented on docs/testnet/update/update-diva-manual.md
> +If you used other than docker-compose.yml as 'docker-compose-with-clients-metrics.yml' you can specify it:
Other what? Specify what?

2023-09-16 14:38 UTC, pradavc commented on docs/testnet/update/update-diva-manual.md
> +Create a fresh Diva (in a different folder of your choice):
What does it mean "Create a fresh Diva"?

2023-09-16 14:38 UTC, pradavc commented on docs/testnet/update/update-diva-manual.md
> +```
```suggestion
```bash
cd ~/
git clone https://github.com/shamirlabs/diva-alpha-net ~/diva-alpha-net
```

2023-09-16 14:38 UTC, pradavc commented on docs/testnet/update/update-diva-manual.md
> +### 2. Create a new diva-alpha-net
This section should go after the backup of files, not before.

2023-09-16 14:38 UTC, pradavc commented on docs/testnet/update/update-diva-manual.md
> +### 3. Copy the database
The backup of these files should go before cloning anything new, and it should be as simple as:

```
mv ~/diva-alpha-net ~/diva-alpha-net-bak
```

2023-09-16 14:38 UTC, pradavc commented on sidebars.js
> +              id: 'testnet/update/update-diva-manual',
Since files are already inside the update folder, "update-diva" in the filename becomes redundant. Rename files simply to manual.md and auto.md.

2023-09-17 19:30 UTC, franjoespejo commented
@pradavc new version including all your suggestions plus a simpler structure as discussed

2023-09-18 13:43 UTC, franjoespejo commented on docs/testnet/update/update-diva-auto.md
> +Please note this is only available for those with the latest versions of the docker compose for diva-alpha-net.
Good points, there is not a versioning for the docker compose but we can use commit ids instead. Will add them, thanks!

2023-09-18 13:43 UTC, franjoespejo commented on docs/testnet/update/update-diva-manual.md
> + Manual migration/update is always a useful option for any version of diva-alpha-net. For the earliest versions of the diva-alpha-net it is needed for the upload since automatic scripts are not backw
agreed, will update

2023-09-18 13:44 UTC, micho commented on docs/testnet/update/update-diva-auto.md
> +Please note this is only available for those with the latest versions of the docker compose for diva-alpha-net.
in that case i suggest you mention the date, because in a few months it will be so old that we will be able to remove it hopefully :)

2023-09-20 19:41 UTC, pradavc approved these changes
Ok after review

2023-09-20 19:42 UTC, merged