Known bugs: add concurrency bug
shamirlabs/docs pull request #9
Opened 2023-08-31 10:16 UTC by micho

Add the current bug for validator concurrency, and instructions on how to learn once it's fixed

<img width="1036" alt="image" src="https://github.com/shamirlabs/docs/assets/323401/9f292195-038b-4f1a-a7c1-04ca6d0034e0">

2023-08-31 11:44 UTC, pradavc requested changes

2023-08-31 11:44 UTC, pradavc commented on docs/testnet/known-bugs.md
> +When using the file `docker-compose-with-clients-metrics.yml` or `docker-compose-with-clients.yml`, the Diva client will wait until the Ethereum nodes are synced without being able to start. If that
These files don't exist anymore. Since you are changing this section, please update accordingly.

2023-08-31 11:44 UTC, pradavc commented on docs/testnet/known-bugs.md
> +The current Diva version doesn't require any collateral to receive validator key shares. You will start receiving them simply by remaining online. As new ETH is staked into Diva, validators will be c
```suggestion
The current Diva version doesn't require any collateral to receive validator key shares. You will start receiving them simply by remaining online. As new ETHs are staked into Diva, validators will be created, and you will have a chance to receive some of the new randomly assigned key shares.
```

2023-08-31 14:17 UTC, micho commented on docs/testnet/known-bugs.md
> +When using the file `docker-compose-with-clients-metrics.yml` or `docker-compose-with-clients.yml`, the Diva client will wait until the Ethereum nodes are synced without being able to start. If that
i didnt change this text, and feel underqualified to do it. could you update it? either in this PR or next one

this PR is just adding a header to this section

2023-09-05 10:23 UTC, micho commented on docs/testnet/known-bugs.md
> +When using the file `docker-compose-with-clients-metrics.yml` or `docker-compose-with-clients.yml`, the Diva client will wait until the Ethereum nodes are synced without being able to start. If that
ping here

2023-09-08 12:41 UTC, pradavc commented on docs/testnet/known-bugs.md
> +When using the file `docker-compose-with-clients-metrics.yml` or `docker-compose-with-clients.yml`, the Diva client will wait until the Ethereum nodes are synced without being able to start. If that
I don't have time to do it, but we should only merge a PR if we know things are right. It is as easy as changing it with the files that are in the testnet repo: https://github.com/shamirlabs/diva-alpha-net

If you can't do it, I will do it when I find time.

2023-09-08 12:51 UTC, micho commented on docs/testnet/known-bugs.md
> +When using the file `docker-compose-with-clients-metrics.yml` or `docker-compose-with-clients.yml`, the Diva client will wait until the Ethereum nodes are synced without being able to start. If that
this code wasn't edited, it's unrelated to the PR. i simply added a header. the real fix is below

2023-09-08 12:57 UTC, merged